### PR TITLE
Tweak dependencies

### LINKED ISSUE #368: Optimise dependencies based on TFM
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
System.Collection can be provided via the framework ie net Standard 2.0 & net 6 as such conditions should be placed on it so that it is only included for net framework.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by thompson-tomo**
Restrict TFM's which System.Collection is added for to reduce dependency graph

Closes #368

### CODE REVIEW

**Comment by doghappy** [comment]
Thanks for you PR, but I don't why need to change, could you please leave extra infos to explain it?

**Comment by thompson-tomo** [comment]
when a library is compiled for a particular framework ie Net 6 a number of dependencies are provided by the framework hence the developer/publisher is not needing to include them in their release for those frameworks. 
In this case System.Collections is bundled in to the Framework starting with Net core 5 i think hence when compiling for a newer framework ie Net 6 that explicit dependency is not needed. This is why i have placed a condition so that the package is only included when it is actually needed due to the framework not providing it.

**Comment by doghappy** [comment]
Hi @thompson-tomo thanks for your advice, may I ask how to check if a package included in target framework or not

**Comment by thompson-tomo** [comment]
hi @doghappy the easiest way i have found is adding the additional Target frameworks to the project, then expanding the dependencies in the project tree and checking what is included.

image

**Comment by doghappy** [comment]
I think we can remove both dependencies:
1. System.Collections
2. System.Net.Http

**Comment by doghappy** [comment]
reverted lot of code. and removed those 2 dependencies.

**Comment by thompson-tomo** [comment]
Handled via https://github.com/doghappy/socket.io-client-csharp/commit/cc4c7f1c25de142c8c1aae5d35ebeeb3cf1ff8c0

**Pull request closed without merging**
